name: Slack-Integration
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step fail
        run: ec fail
      - uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
           SLACK_WEBHOOK: ${{ secrets.slack_secret }}
           SLACK_COLOR: ${{ job.status }}
           SLACK_TITLE: Job Failed
           SLACK_MESSAGE: 'Build completed for ${{ GITHUB.WORKFLOW }} number ${{ GITHUB.RUN_NUMBER }}'
# Generate Slack Secret from https://techlanders-workspace.slack.com/apps/A0F7XDUAZ-incoming-webhooks
